services:
  web:
    image: nginx:alpine
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - flask
    networks:
      - app-network

  flask:
    build:
      context: ./app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - FLASK_APP=app.py
    networks:
      - app-network
    secrets:
      - mongodb_password
      - apiKey

  db:
    build: ./db
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongodb_password
      MONGO_INITDB_DATABASE: movies
    ports:
      - "27017:27017"
    volumes:
      - ./db/data:/data/db
    networks:
      - app-network
    secrets:
      - mongodb_password

  postfix:
    image: juanluisbaptiste/postfix
    container_name: postfix
    env_file:
      - ./postfix.env
    ports:
      - "25:25"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

secrets:
  mongodb_password:
    file: mongodb_password.txt
  apiKey:
    file: apiKey.txt