services:
  web:
    image: nginx:alpine
    volumes:
      - ./web:/usr/share/nginx/html
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - flask
    networks:
      - app-network

  flask:
    build:
      context: ./app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - MONGODB_PASSWORD=/run/secrets/mongodb_password
    networks:
      - app-network
    secrets:
      - mongodb_password
    volumes:
      - ./app:/app

  db:
    build: ./db
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongodb_password
      MONGO_INITDB_DATABASE: movies
    ports:
      - "27017:27017"
    volumes:
      - ./db/data:/data/db
    networks:
      - app-network
    secrets:
      - mongodb_password

  postfix:
    image: juanluisbaptiste/postfix
    container_name: postfix
    environment:
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=noreply.cinemadocker@gmail.com
      - SMTP_PASSWORD=sowqdyofphdrayeh
      - SERVER_HOSTNAME=gmail.com
      - ALWAYS_ADD_MISSING_HEADERS=yes
      - SMTP_USE_TLS=yes
    ports:
      - "25:25"
    networks:
      - app-network
    volumes:
      - postfix-data:/var/spool/postfix
      - postfix-logs:/var/log/mail

volumes:
  postfix-data:
  postfix-logs:

networks:
  app-network:
    driver: bridge

secrets:
  mongodb_password:
    file: mongodb_password.txt