services:
  web:
    image: nginx:alpine
    volumes:
      - ./web:/usr/share/nginx/html
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - flask
    networks:
      - app-network

  flask:
    build:
      context: ./app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - MONGODB_PASSWORD=/run/secrets/mongodb_password
    networks:
      - app-network
    secrets:
      - mongodb_password

  db:
    build: ./db
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongodb_password
      MONGO_INITDB_DATABASE: movies
    ports:
      - "27017:27017"
    volumes:
      - ./db/data:/data/db
    networks:
      - app-network
    secrets:
      - mongodb_password

networks:
  app-network:
    driver: bridge

secrets:
  mongodb_password:
    file: mongodb_password.txt